services:
  freshclam:
    build:
      context: ./packages/clamav
    image: byteshare/clamav:1.0.0
    restart: on-failure
    environment:
      MODE: freshclam
    volumes:
      - config:/etc/clamav
      - data:/var/lib/clamav
    networks:
      - byteshare-network

  clamav:
    build:
      context: ./packages/clamav
    image: byteshare/clamav:1.0.0
    restart: on-failure
    depends_on:
      - freshclam
    environment:
      MODE: clamd
      CLAMAV_TCP_ADDRESS: 0.0.0.0
      CLAMAV_TCP_PORT: 3310
    ulimits:
      stack: 1048576
    volumes:
      - config:/etc/clamav
      - data:/var/lib/clamav
    networks:
      - byteshare-network
  
  moderation:
    build:
      context: ./app
    image: byteshare/moderation:1.0.0
    restart: unless-stopped
    environment:
      - R2_ACCOUNT_ID
      - R2_BUCKET_NAME
      - R2_ACCESS_KEY
      - R2_SECRET_KEY
      - RABBITMQ_QUEUE
      - RABBITMQ_URL
      - MIDDLEWARE_BASE_URL
      - MIDDLEWARE_API_KEY
      - CLAMAV_HOST
    depends_on:
      - clamav
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - byteshare-network

networks:
  byteshare-network:
    driver: bridge

volumes:
  config:
  data: