name: Build & Deploy Docker Images to Docker Hub

on:
  release:
    types: [created]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        version: ${{ github.event.release.tag_name }}

    - name: Build ClamAV Docker image
      run: docker build -t byteshare/clamav:$version .

    - name: Push ClamAV Docker image to Docker Hub
      run: docker push byteshare/clamav:$version
    
    - name: Build Moderation Docker image
      run: docker build -t byteshare/moderation:$version .

    - name: Push Moderation Docker image to Docker Hub
      run: docker push byteshare/moderation:$version

